[tool.poetry]
name = "alcohol_control_package"
version = "1.1.0"
description = ""
authors = ["kgrid developers <kgrid-developers@umich.edu>"]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
