openapi: 3.0.0
info:
  version: '1.0'
  title: QALY Gain By Stop Using Alcohol
  description: qaly gain by stop using alcohol
servers:
  - url: /endpoints/99999/alcohol/v1.1.0
    description: qaly gain by stop using alcohol
paths:
  /qalygain:
    post:
      description: qaly gain by stop using alcohol
      operationId: alcoholqalygain
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
components:
  schemas:
    input:
      required:
        - features
      properties:
        features:
          type: object
          properties:
            id:
              type: string
            features:
              type: object
          example:
            $ref: https://demo.kgrid.org/schemas/takslerr01PtFeaturesSample.json#/patient/features
    output:
      required:
        - result
      properties:
        result:
          type: object
